server:
  port: 7001

spring:
  application:
    name: guli-provider-user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT
    username: root
    password: root
    #jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # Redis数据库
  redis:
    database: 0
    host: 106.15.187.32
    password: 123456
    port: 12312
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: -1

#整合mybatisplus
mybatis-plus:
  type-aliases-package: com.guli.pojo
  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: false
      logic-delete-value: 0
      logic-not-delete-value: 1
      refresh: true

eureka:
  client: #客户端注册进eureka服务列表内
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    #    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka
      #Eureka服务器集群
      #defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: guli-provider-user7001
    prefer-ip-address: true     #访问路径可以显示IP地址



