server:
  port: 8001

guli-web:
  upload-location: D:/Users/YT/IdeaProjects/guli/guli-web/src/main/resources/static/video/
eureka:
  client:
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: guli-web8001
    prefer-ip-address: true     #访问路径可以显示IP地址



spring:
  application:
    name: guli-web
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
      encoding: utf-8
      cache: false
      suffix: .html
      prefix: classpath:/templates/showWeb/
      servlet:
        content-type: text/html

  mvc:
    view:
      prefix: /
      suffix: .html

    #映射静态资源
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/templates/showWeb/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
  # Redis数据库
  redis:
    database: 0
    host: 106.15.187.32
    password: 123456
    port: 12312
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: -1
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB
xuecheng:
  fastdfs:
    connect_timeout_in_seconds: 5000
    network_timeout_in_seconds: 30003
    charset: UTF-8
    tracker_servers: 39.106.18.84:22122 #多个 trackerServer中间以逗号分隔

#整合mybatisplus
mybatis-plus:
  type-aliases-package: com.cssl.mapper
  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: false
      logic-delete-value: 0
      logic-not-delete-value: 1
      refresh: true