server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:123456@localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processtask: queue_media_video_processtask
    routingkey-media-video: routingkey_media_video
  video-location: D:/test/video/
  ffmpeg-path: D:/test/ffmpeg-20190916-ef50cf7-win64-static/bin/ffmpeg.exe